"""Add created_at field

Revision ID: 73062af07da0
Revises: 993ab627fb4a
Create Date: 2025-03-19 08:50:43.897203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73062af07da0'
down_revision = '993ab627fb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('supplier_shipper', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bom_material_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('material_size', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('container_count', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pod', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.String(length=100), nullable=True))
        batch_op.drop_column('booking_eta')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('booking_eta', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('estimated_delivery_date')
        batch_op.drop_column('pod')
        batch_op.drop_column('container_count')
        batch_op.drop_column('unit')
        batch_op.drop_column('material_size')
        batch_op.drop_column('bom_material_name')
        batch_op.drop_column('supplier_shipper')
        batch_op.drop_column('input_number')

    # ### end Alembic commands ###
