"""Reinitialize database

Revision ID: 993ab627fb4a
Revises: 
Create Date: 2025-03-04 12:21:07.317725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993ab627fb4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbl_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hbl_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('container_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pol', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('etd', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('booking_eta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pod_eta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('material_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.String(length=100), nullable=True))
        batch_op.drop_column('supplier')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('bom_name')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('bom_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('quantity')
        batch_op.drop_column('material_code')
        batch_op.drop_column('pod_eta')
        batch_op.drop_column('booking_eta')
        batch_op.drop_column('etd')
        batch_op.drop_column('pol')
        batch_op.drop_column('container_number')
        batch_op.drop_column('hbl_number')
        batch_op.drop_column('mbl_number')

    # ### end Alembic commands ###
